la dernière instruction de cette cellule permet d’éviter l’affichage inutile de certains messages d’informations de tensorflow.

In [1]:
import tensorflow as tf 
import os
import numpy as np 

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

2024-03-19 14:23:14.835201: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-19 14:23:14.914780: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-19 14:23:14.914814: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-19 14:23:14.916678: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-19 14:23:14.927921: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-19 14:23:14.928425: I tensorflow/core/platform/cpu_feature_guard.cc:1

Dans ce code, la variable B est un tensor qui est associé à un tableau à deux dimensions. Les valeurs de B ont été déclarées avec les deux valeurs réelles 1. et 2. et toutes les autres valeurs ont été fixées avec des valeurs entières. 

In [2]:
B = tf.constant([[1.,2.,3],[4,5,6],[7,8,9]])

print(f"B = {B}")

B = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Les valeurs de B qui ont été déclarées avec des valeurs entières ont toutes été transformées en valeurs réelles ! Il suffit qu’il y ait une valeur réelle pour que TensorFlow considère que toutes les valeurs sont réelles. En effet, c’est tout à fait logique puisqu’avec le type des valeurs réelles on peut représenter toute valeur entière, mais pas l’inverse.

In [3]:
print(f"B.shape = {B.shape}")
print(f"B.dtype = {B.dtype}")

B.shape = (3, 3)
B.dtype = <dtype: 'float32'>


Remarquez que par défaut le type des réels utilisé par TensorFlow est float32, contrairement à la bibliothèque numpy qui considère par défaut que le type des réels est le type float64.

Pour accéder aux valeurs d’un tensor, on utilise la même notation que celle utilisée pour accéder aux valeurs d’un tableau numpy !

L’instruction suivante permet d’afficher les lignes du tensor B en ignorant la première ligne, c’est-à-dire la ligne d’indice 0, et les deux premières colonnes en ignorant la dernière colonne. 

In [5]:
print(f"B[:,:] = {B[:,:]}") 

B[:,:] = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [17]:
print(f"{B[1:,:2]}")

[[4. 5.]
 [7. 8.]]


Les opérations arithmétiques peuvent être réalisées comme avec les tableaux numpy. Par exemple, le code suivant permet d’ajouter la valeur 100 au tensor B.

In [4]:
print(f"B+100 =\n {B+100}")

B+100 =
 [[101. 102. 103.]
 [104. 105. 106.]
 [107. 108. 109.]]


L’opération d’addition précédente aurait pu être réalisée en utilisant la méthode add de TensorFlow 

In [6]:
print(f"B+100 =\n {tf.add(B,495)}")  


B+100 =
 [[496. 497. 498.]
 [499. 500. 501.]
 [502. 503. 504.]]


Nous pouvons créer des tensors à partir de tableaux numpy. L’exemple suivant montre comment créer le tensor tf_tensor à partir du tableau numpy np_array_1.

In [50]:
np_array_1 = np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
tf_tensor = tf.constant(np_array_1)
print("np_array_1 :", np_array_1)
print("tf_tensor : ",tf_tensor) 

np_array_1 : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
tf_tensor :  tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float64)


Remarquez que cette fois TensorFlow a créé le tensor tf_tensor avec le type float64 et non pas le type float32 comme il aurait dû le faire, puisque les nombres réels sont représentés par défaut avec le type float32 ! C’est tout à fait normal car le tensor tf_tensor a été créé à partir d’un tableau numpy, et dans ce dernier les nombres réels sont représentés avec le type float64 et TensorFlow a réutilisé le type de np_array_1, donc le type float64, pour la création de tf_tensor.  

On peut également réaliser l’opération inverse à l’opération précédente en créant un tableau numpy à partir d’un tensor ! Le code suivant permet de créer le tableau numpy np_array_2 à partir du tensor tf_tensor.

In [23]:
np_array_2 = tf_tensor.numpy()
print("np_array_2 : ", np_array_2) 

np_array_2 :  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Un point important auquel il faut faire attention est le type des tensors lorsque nous les utilisons dans des opérations arithmétiques.

Par exemple, le code suivant va générer une erreur à l’exécution, car le type du tensor a est float64 alors que le type du tensor b est le type par défaut, à savoir float32.

In [7]:
a=tf.constant(10., dtype="float64")
b = tf.constant(10.) 
print(f"a+b = {a+b}") #cette instruction va afficher une erreur à l'exécution

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2] name: 

En effet, le code de cette dernière cellule, si vous tentez de l’exécuter, va lancer une erreur puisque pour TensorFlow il n’est pas possible d’additionner des float64 avec des float32 !

Contrairement à ce que nous avons l’habitude de faire avec les langages de programmation classiques où nous pouvons réaliser des opérations arithmétiques entre des nombres réels même s’ils ne sont pas de même taille, TensorFlow considère que le fait de tenter une opération arithmétique entre des données de tailles différentes est dû à une erreur de conception.

Ainsi, pour pouvoir réaliser l’opération d’addition précédente, il serait nécessaire de transformer l’un des deux opérandes vers le type de l’autre opérande. Le code suivant transforme l’opérande a qui était de type float64 vers le type float32.

In [8]:
a=tf.constant(10., dtype="float64")
b = tf.constant(10.) 

a=tf.cast(a, tf.float32 )
print(f"a+b = {a+b}")


a+b = 20.0


Les tensors que nous avons eu l’occasion de manipuler à la section précédente sont des constantes, c’est-à-dire qu’une fois qu’ils ont été créés, nous ne pouvons pas modifier leurs valeurs.

Les tensors dont les valeurs sont modifiables peuvent être créés avec la méthode Variable. Le code suivant crée le tensor tensor_1 en l’initialisant avec un tableau à deux dimensions, puis modifie les valeurs de ce tableau en utilisant la méthode assign.

In [8]:
tensor_1 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
 
print(f"tensor_1 = \n{tensor_1}")

tensor_1.assign(tensor_1 * 100)
print(f"tensor_1 = \n{tensor_1}")

tensor_1 = 
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>
tensor_1 = 
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]], dtype=int32)>


Il existe des méthodes de TensorFlow qui permettent d’initialiser les valeurs d’un tensor. Par exemple, le code suivant utilise la méthode zeros pour créer un tensor et l’associer à un tableau à deux dimensions, trois lignes et trois colonnes, dont toutes les valeurs sont égales à 0.

In [10]:
tensor_2 = tf.zeros((3,4))
print(f"tensor_2 = \n{tensor_2}")

tensor_2 = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

On peut également initialiser un tensor avec des valeurs générées de manière aléatoire.
Ce code génère un tensor associé à un tableau de quatre lignes et quatre colonnes dont les valeurs seront générées de manière pseudo-aléatoire, mais comprises entre 1 et 100

In [13]:
tensor_3 = tf.random.uniform((4,4), minval=1, maxval=100)
print(f"tensor_3 = \n{tensor_3}")

tensor_3 = 
[[44.98834   66.59426   31.01627   39.657845 ]
 [86.256805  74.088806  85.98891   90.65248  ]
 [46.11658   10.466301  13.400728  65.031975 ]
 [49.157013   3.4360874 89.44271   37.077644 ]]


Dans ce dernier exemple de méthodes d’initialisation des tensors, nous avons utilisé la méthode fill afin de choisir explicitement la valeur avec laquelle nous souhaitons initialiser le tensor tensor_4 et qui est la valeur 5.

In [44]:
tensor_4 = tf.fill((3,3), value = 5) 
print(f"tensor_4 = \n{tensor_4}")

tensor_4 = 
[[5 5 5]
 [5 5 5]
 [5 5 5]]


Avec TensorFlow, nous pouvons effectuer toutes les opérations algébriques que nous pouvons réaliser avec les tableaux numpy. À titre d’exemple, le code suivant réalise la multiplication des deux matrices associées aux deux tensors tensor_5 et tensor_6. La multiplication est réalisée grâce à la méthode matmul de TensorFlow.

Le résultat de cette multiplication est stocké dans le tensor tensor_7

In [47]:
tensor_5 = tf.fill((2,3), 1) 
tensor_6 = tf.fill((3,2), 2) 
print(f"tensor_5 = \n{tensor_5}")
print(f"tensor_6 = \n{tensor_6}")

tensor_7 = tf.matmul(tensor_5, tensor_6)
print(f"tensor_7 = \n{tensor_7}")

tensor_5 = 
[[1 1 1]
 [1 1 1]]
tensor_6 = 
[[2 2]
 [2 2]
 [2 2]]
tensor_7 = 
[[6 6]
 [6 6]]
